---
- name: Update YUM
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: Install system tools
  include: system-tools.yml
  tags: system-tools

- name: Install environment dependencies
  include: environment-dependencies.yml
  tags: environment-dependencies

- name: Configure NTP
  include: ntp.yml
  tags: ntp
